model_name: "gpt-3.5-turbo"
input_file: "tests/test.pdf"
output_file_format: "markdown"
source_language: "English"
target_language: "Chinese"
openai_api_key: "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"